import { Avatar, Badge, Button } from '@tutti-os/ui-system';
import { ArrowRightIcon, CheckIcon, FileTextIcon, MessageSquareTextIcon, TaskIcon, UserLinedIcon } from '@tutti-os/ui-system/icons';
import { statusLabels, timeLabel, type Document, type State, type Task } from '../../shared/api';
import { Empty } from '../../shared/ui';
import type { View } from './Sidebar';

export function ContextPanel({ state, onDocument, onThread }: { state: State; onDocument: (d: Document) => void; onThread: (id: string) => void }) {
  const pending = state.threads.filter(t => t.target_id === state.me && ['waiting','human'].includes(t.status));
  return <aside className="context-panel" aria-label="项目上下文"><div className="context-title"><span>项目上下文</span><span className="subtle-label">共享</span></div><h3>一起推进的事情</h3><p className="context-description">让信息先流动，让判断留给人。</p>
    <div className="context-label">共享资料 <span>{state.documents.length}</span></div><div className="context-documents">{state.documents.map(d => <button key={d.id} className="context-doc" onClick={() => onDocument(d)}><span className="file-tile"><FileTextIcon size={18} /></span><span><strong>{d.title}</strong><small>团队可见 · 文档</small></span></button>)}</div>
    <div className="context-label">团队成员 <span>{state.members.length}</span></div>{state.members.map(m => <div className="context-member" key={m.id}><Avatar label={m.person_name} initial={m.person_name[0]} size={24} /><span>{m.person_name}{m.id === state.me && <small> 你</small>}</span><span className={`availability ${m.window === 'closed' ? 'focused' : ''}`}>{m.window === 'closed' ? '专注中' : '可协作'}</span></div>)}
    <div className="context-inbox"><div><CheckIcon size={15} /><strong>需要你的判断</strong></div>{pending.length ? pending.slice(0,2).map(t => <button key={t.id} onClick={() => onThread(t.id)}><span>{t.title}</span><ArrowRightIcon size={13} /></button>) : <p>暂时没有待拍板事项。<br />Agent 接住的信息会留在协作记录里。</p>}</div>
    <div className="context-footer"><span className="status-dot" />数据保存在本机</div>
  </aside>;
}

export function Lists({ view, state, busy, onMember, onThread, onDocument, onPublish, onTask }: {
  view: View; state: State; busy: boolean; onMember: (id: string) => void; onThread: (id: string) => void; onDocument: (d: Document) => void; onPublish: () => void; onTask: (task: Task) => void;
}) {
  if (view === 'people') return <div className="content-page"><div className="page-intro"><span className="eyeline">团队协作</span><h1>先问 Agent，再找本人</h1><p>日常问题先由专属 Agent 接住，需要判断时再把话递给同事。</p></div><div className="member-list">{state.members.filter(m => m.id !== state.me).map(m => <article className="member-row" key={m.id}><Avatar label={m.person_name} initial={m.person_name[0]} size={44} /><div><h2>{m.person_name}<Badge variant="secondary" size="sm">{m.window === 'closed' ? '本人专注中' : '可协作'}</Badge></h2><p>{m.tags.join(' · ')}</p><small>Agent 可查阅团队共享资料</small></div><Button variant="secondary" disabled={busy} onClick={() => onMember(m.id)}><MessageSquareTextIcon />问 Agent</Button></article>)}</div><div className="inline-explanation"><UserLinedIcon size={16} /><p>进入的是对方的 Agent 通道。点击“找本人”后，当前协作记录才会交给对方。</p></div></div>;
  if (view === 'inbox') { const items = state.threads.filter(t => t.target_id === state.me && ['waiting','human'].includes(t.status)); return <div className="content-page"><div className="page-intro"><span className="eyeline">把注意力留给重要的事</span><h1>待我拍板 <span>{items.length}</span></h1><p>Agent 已把信息接住，这些事情需要你判断。</p></div>{items.length ? <div className="decision-list">{items.map(t => <article className="decision-card" key={t.id}><div className="decision-meta"><Badge variant="pending">{statusLabels[t.status]}</Badge><time>{timeLabel(t.updated_at)}</time></div><h2>{t.title}</h2><p>{t.handoff_note || '查看协作记录，回复你的判断。'}</p><div className="decision-bottom"><span>{state.members.find(m => m.id === t.owner_id)?.person_name} 发起</span><Button onClick={() => onThread(t.id)}>查看并处理<ArrowRightIcon /></Button></div></article>)}</div> : <Empty icon={<CheckIcon size={24} />} title="暂时没有需要你拍板的事">新请求送达时会出现在这里。</Empty>}</div>; }
  if (view === 'tasks') return <div className="content-page"><div className="page-intro"><span className="eyeline">从判断到行动</span><h1>我的待办</h1><p>只记录已经由本人确认的任务。</p></div>{state.tasks.length ? <div className="task-list">{state.tasks.map(task => <article className={`task-row ${task.status === 'done' ? 'done' : ''}`} key={task.id}><Button size="icon-sm" variant={task.status === 'done' ? 'secondary' : 'outline'} aria-label={`${task.status === 'done' ? '重新打开' : '完成'}：${task.title}`} disabled={busy || task.assignee_id !== state.me} onClick={() => onTask(task)}>{task.status === 'done' ? <CheckIcon /> : <span />}</Button><div><button onClick={() => onThread(task.thread_id)}>{task.title}</button><p>{task.detail}</p><small>{state.members.find(m => m.id === task.assignee_id)?.person_name} 负责 · 本人已确认</small></div><Badge variant={task.status === 'done' ? 'success' : 'secondary'}>{task.status === 'done' ? '已完成' : '待推进'}</Badge></article>)}</div> : <Empty icon={<TaskIcon size={24} />} title="下一步，明确下来">协作经过本人确认后，任务会自动出现在这里。</Empty>}</div>;
  return <div className="content-page"><div className="page-intro page-intro-actions"><div><span className="eyeline">团队共同的上下文</span><h1>共享成果</h1><p>明确发布的材料，才会成为 Agent 代答的依据。</p></div><Button onClick={onPublish}><FileTextIcon />发布资料</Button></div><div className="document-list">{state.documents.map(d => <button className="document-row" key={d.id} onClick={() => onDocument(d)}><span className="file-tile"><FileTextIcon size={20} /></span><span><strong>{d.title}</strong><small>{d.body.replaceAll('\n',' ').slice(0,70)}</small></span><span className="document-owner">{state.members.find(m => m.id === d.unit_id)?.person_name}</span><ArrowRightIcon size={14} /></button>)}</div></div>;
}
