import { Avatar, Badge, Button } from '@tutti-os/ui-system';
import { ArrowRightIcon, CheckIcon, FileTextIcon, MessageSquareTextIcon, TaskIcon, UserLinedIcon } from '@tutti-os/ui-system/icons';
import { statusLabels, timeLabel, type Document, type State, type Task } from '../../shared/api';
import { Empty } from '../../shared/ui';
import type { View } from './Sidebar';

export function Lists({ view, state, busy, onMember, onThread, onDocument, onPublish, onSettings, onTask }: {
  view: View; state: State; busy: boolean; onMember: (id: string) => void; onThread: (id: string) => void; onDocument: (d: Document) => void; onPublish: () => void; onSettings: () => void; onTask: (task: Task) => void;
}) {
  if (view === 'people') return <div className="content-page"><div className="page-intro"><h1>找同事</h1></div>{state.members.length===1 && <Empty icon={<UserLinedIcon size={24} />} title="邀请同事一起协作">{state.account.role==='owner' ? <Button variant="secondary" onClick={onSettings}>邀请成员</Button> : '其他成员加入后，会显示在这里。'}</Empty>}<div className="member-list">{state.members.filter(m => m.id !== state.me).map(m => <article className="member-row" key={m.id}><Avatar label={m.person_name} initial={m.person_name[0]} size={44} /><div><h2>{m.person_name}<Badge variant="secondary" size="sm">{m.window === 'closed' ? '本人专注中' : '可协作'}</Badge></h2><p>{m.tags.join(' · ')}</p></div><Button variant="secondary" disabled={busy} onClick={() => onMember(m.id)}><MessageSquareTextIcon />问 Agent</Button></article>)}</div></div>;
  if (view === 'inbox') { const items = state.threads.filter(t => t.target_id === state.me && ['waiting','human'].includes(t.status)); return <div className="content-page"><div className="page-intro"><h1>需要你 <span>{items.length}</span></h1></div>{items.length ? <div className="decision-list">{items.map(t => <article className="decision-card" key={t.id}><div className="decision-meta"><Badge variant="pending">{statusLabels[t.status]}</Badge><time>{timeLabel(t.updated_at)}</time></div><h2>{t.title}</h2><p>{t.handoff_note}</p><div className="decision-bottom"><span>{state.members.find(m => m.id === t.owner_id)?.person_name} 发起</span><Button onClick={() => onThread(t.id)}>处理<ArrowRightIcon /></Button></div></article>)}</div> : <Empty icon={<CheckIcon size={24} />} title="暂无待处理请求" />}</div>; }
  if (view === 'tasks') return <div className="content-page"><div className="page-intro"><h1>我的待办</h1></div>{state.tasks.length ? <div className="task-list">{state.tasks.map(task => <article className={`task-row ${task.status === 'done' ? 'done' : ''}`} key={task.id}><Button size="icon-sm" variant={task.status === 'done' ? 'secondary' : 'outline'} aria-label={`${task.status === 'done' ? '重新打开' : '完成'}：${task.title}`} disabled={busy || task.assignee_id !== state.me} onClick={() => onTask(task)}>{task.status === 'done' ? <CheckIcon /> : <span />}</Button><div><button onClick={() => onThread(task.thread_id)}>{task.title}</button><p>{task.detail}</p><small>{state.members.find(m => m.id === task.assignee_id)?.person_name} 负责 · 本人已确认</small></div><Badge variant={task.status === 'done' ? 'success' : 'secondary'}>{task.status === 'done' ? '已完成' : '待推进'}</Badge></article>)}</div> : <Empty icon={<TaskIcon size={24} />} title="暂无待办" />}</div>;
  return <div className="content-page"><div className="page-intro page-intro-actions"><div><h1>共享成果</h1></div><Button onClick={onPublish}><FileTextIcon />发布资料</Button></div>{!state.documents.length && <Empty icon={<FileTextIcon size={24} />} title="暂无共享资料"><Button variant="secondary" onClick={onPublish}>发布资料</Button></Empty>}<div className="document-list">{state.documents.map(d => <button className="document-row" key={d.id} onClick={() => onDocument(d)}><span className="file-tile"><FileTextIcon size={20} /></span><span><strong>{d.title}</strong><small>{d.body.replaceAll('\n',' ').slice(0,70)}</small></span><span className="document-owner">{state.members.find(m => m.id === d.unit_id)?.person_name}</span><ArrowRightIcon size={14} /></button>)}</div></div>;
}
